image_config: &image_config
  IMAGE_NAME: moxspec-centos
  IMAGE_TAG: 7

version: 2
jobs:
  build:
    machine: true
    environment:
      <<: *image_config
    steps:
      - checkout
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run: docker build -t actapio/$IMAGE_NAME:$IMAGE_TAG -f Dockerfile .
      - run: docker push actapio/$IMAGE_NAME:$IMAGE_TAG && sleep 10
      - store_artifacts:
          path: Dockerfile
  test_image:
    environment:
      <<: *image_config
    docker:
      - image: actapio/$IMAGE_NAME:$IMAGE_TAG
        auth:
            username: $DOCKER_USERNAME
            password: $DOCKER_PASSWORD
    steps:
      - checkout
      - run:
          name: print go version
          command: go version
workflows:
  version: 2
  dockerfile:
    jobs:
      - build:
          context: moxspec
      - test_image:
          context: moxspec
          requires:
            - build
